name: adflaunt
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  app_settings: ^5.0.0
  bottom_sheet_draggable: ^1.0.4+1
  cached_network_image: ^3.2.3
  camera: ^0.10.5+2
  country_code_picker: ^3.0.0
  currency_text_input_formatter: ^2.1.10
  curved_progress_bar: ^1.0.2
  custom_ratio_camera: ^0.0.3
  draggable_bottom_sheet: ^1.0.2
  dropdown_button2: ^2.3.6
  easy_stepper: ^0.7.2
  equatable: ^2.0.5
  fine_stepper: ^0.2.0+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_email_sender: ^6.0.1
  flutter_stripe: ^9.3.0
  flutter_svg: ^2.0.7
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.1
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  http: ^1.1.0
  image_picker: ^1.0.1
  interactive_maps_marker:
    git:
      url: https://github.com/berkeenesakt/interactive_maps_marker_flutter
  intl: ^0.18.0
  json_annotation: ^4.8.1
  loading_indicator: ^3.1.1
  otp_text_field: ^1.1.3
  path_provider: ^2.0.15
  percent_indicator: ^4.2.3
  reorderable_grid_view: ^2.2.6
  modal_bottom_sheet: ^3.0.0-pre
  sign_in_with_apple: ^5.0.0
  widget_to_marker: ^1.0.4
  google_places_flutter: ^2.0.6
  syncfusion_flutter_sliders: ^22.2.5
  syncfusion_flutter_core: ^22.2.5
  google_maps_utils: ^1.5.1+0
  salomon_bottom_bar: ^3.3.2
  page_view_dot_indicator:
    git:
      url: https://github.com/berkeenesakt/page_view_dot_indicator.git
  crypto: ^3.0.3
  socket_io_client: ^2.0.2
  flutter_chat_ui: ^1.6.9
  flutter_chat_types: ^3.6.2
  uuid: ^3.0.7
  flutter_cache_manager: ^3.3.1
  syncfusion_flutter_datepicker: ^22.2.8
  file_picker: ^5.3.3
  archive: ^3.3.7
  syncfusion_flutter_calendar: ^22.2.8
  table_calendar: ^3.0.9
  paged_vertical_calendar: ^1.1.6
  hive_flutter: ^1.1.0
  connectivity_plus: ^4.0.2
  share_plus: ^7.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0+1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Poppins/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins/Poppins-Regular.ttf
        - asset: assets/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/Poppins/Poppins-Light.ttf
          weight: 300
flutter_intl:
  enabled: true
