class ListingConstants {
  static List<String> types = [
    "Outdoor",
    "Indoor",
    "Vehicle",
  ];

  static List<String> spaceType = [
    "Spanish Restaurant",
    "Chinese Restaurant",
    "Italian Restaurant",
    "Barber Shop",
    "Parking Lot",
    "SUV",
    "Truck",
    "Car",
    "Beauty Salon",
    "Nail Salon",
    "Sneaker Store",
    "Fast Food",
    "Building",
    "Church",
    "Office",
    "Warehouse",
    "Retail",
    "Night Club",
    "Lounge",
    "Smoke Shops",
    "Gym",
    "Liquor Store",
    "Medical",
    "Transportation",
    "Government",
    "Residential",
    "Commercial",
    "Home Based Business",
    "School",
    "Wholesale",
    "Beverages",
    "Food",
    "Fast Food",
    "Building",
    "House",
    "Parking Lot",
    "Lot",
    "Gate",
    "Cannabis",
    "Breakfast",
    "Lunch",
    "Dinner",
    "Highway",
    "Main Street",
    "Adhesive Vylil",
    "Other",
  ];

  static List<String> type = [
    "Banner",
    "Poster",
    "Car Sign",
    "Floor Sign",
    "Car Magnet",
    "Billboard",
    "Bumper Sticker",
    "Yard Sign",
    "Digital",
  ];
}
